/*
CREATE TABLE IF NOT EXISTS ADDRESS (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  ADDRESS_ID VARCHAR(255) NOT NULL,
  HOUSE_NUMBER VARCHAR(255) ,
  STREET VARCHAR(255) ,
  CITY VARCHAR(50) NOT NULL,
  STATE VARCHAR(50) NOT NULL,
  PINCODE integer NOT NULL,
  CUSTOMER_ID integer NOT NULL,
);

alter table if exists ADDRESS
       add constraint FK_ADDRESS_CUSTOMER_ID
       foreign key (CUSTOMER_ID)
       references CUSTOMERS*/
