/*
CREATE DATABASE IF NOT EXISTS CUSTOMER_MANAGEMENT;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CONTACT_NUMBER VARCHAR(255) NOT NULL,
  CREATED_AT timestamp,
  UPDATED_AT timestamp,

);*/
